---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: wordpress-operator
  name: wordpress-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: wordpress-operator
  template:
    metadata:
      labels:
        name: wordpress-operator
    spec:
      serviceAccount: wordpresses-operator-sa
      containers:
        - image: yuxiaoting/wordpress:202210121423
          imagePullPolicy: Always
          name: wordpress-operator
          env:
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: WATCH_NAMESPACE
              value: "xtyudl-lab"
