apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: wordpresses-operator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: wordpresses-operator-role
subjects:
  - kind: ServiceAccount
    name: wordpresses-operator-sa

