---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: wordpresses-operator-role
rules:
  ##
  ## Rules for xtyudl.cic.ibm.com/v1, Kind: WordPress
  ##

  - apiGroups:
      - xtyudl.cic.ibm.com
    resources:
      - wordpresses
    verbs:
      - "*"

  - apiGroups:
      - xtyudl.cic.ibm.com
    resources:
      - wordpresses/status
    verbs:
      - "*"

  - apiGroups:
      - route.openshift.io
    resources:
      - routes
    verbs:
      - "*"

  - apiGroups:
      - "apps"
    resources:
      - deployments
    verbs:
      - "*"

  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - endpoints
      - events
      - configmaps
    verbs:
      - "*"

  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - apply
      - create
      - get
      - delete
      - watch
      - update
      - edit
      - exec
      - list
      - patch
#+kubebuilder:scaffold:rules
